name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**.swift"
      - "**.yml"
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SPM tests
        run: swift test --enable-code-coverage
      - name: Convert coverage files
        run: |
          xcrun llvm-cov export -format "lcov" \
            .build/debug/async-collectionsPackageTests.xctest/Contents/MacOs/async-collectionsPackageTests \
            -ignore-filename-regex="\/Tests\/" \
            -ignore-filename-regex="\/Benchmarks\/" \
            -instr-profile=.build/debug/codecov/default.profdata > info.lcov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          file: info.lcov
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - swift:5.8-jammy
          - swift:5.9-jammy
          - swift:5.10-jammy
          - swiftlang/swift:nightly-6.0-jammy
          - swiftlang/swift:nightly-main-jammy

    container: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          swift test --enable-code-coverage
      - name: Convert coverage files
        run: |
          llvm-cov export -format="lcov" \
            .build/debug/async-collectionsPackageTests.xctest \
            -ignore-filename-regex="\/Tests\/" \
            -ignore-filename-regex="\/Benchmarks\/" \
            -instr-profile .build/debug/codecov/default.profdata > info.lcov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          file: info.lcov
